server:
  port: 8080
  forward-headers-strategy: framework
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:memdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true
  mail:
    host: smtp.gmail.com
    username: project03test@gmail.com
    password: lkaglvozmdjtuirw
    port: 465
    properties:
      "mail.smtp.ssl.enable": true
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
springdoc:
  swagger-ui:
    path: swagger-ui-custom.html
    operationsSorter: method


management:
  endpoints:
    web:
      exposure:
        include: mappings
jwt:
  secret: This is a secret